# 文件读写
定期保存中间结果，避免断电等因素导致没有存上结果
## 加载和保存张量
- load 函数：加载文件
- save 函数：保存文件

In [16]:
import torch
from torch import nn
from torch.nn import functional as F

x=torch.arange(4)
print (x)
torch.save(x,'x-file') # 保存相关的变量，将其存为文件
x2=torch.load('x-file') # 加载文件
print(x2.__len__())

class MLP(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden=nn.Linear(20,256)
        self.output=nn.Linear(256,10)
    def forward(self,X):
        return self.output(F.relu(self.hidden(X)))

net=MLP()
X=torch.randn(size=(2,20))
print(net(X))

# 将此时的权重保存下来
torch.save(net.state_dict(),'mlp.params')

# 加载权重
clone=MLP()
clone.load_state_dict(torch.load('mlp.params'))
a=clone.eval()
print(clone(X)) # 可以看出二者的输出是一样的
print(a)


tensor([0, 1, 2, 3])
4
tensor([[-0.5047, -0.1791, -0.0181, -0.0140, -0.1197, -0.0886, -0.3493, -0.3044,
          0.3395, -0.2083],
        [-0.1517, -0.7108,  0.3556,  0.0333, -0.0869,  0.1280, -0.3427,  0.2008,
         -0.0807,  0.3396]], grad_fn=<AddmmBackward0>)
tensor([[-0.5047, -0.1791, -0.0181, -0.0140, -0.1197, -0.0886, -0.3493, -0.3044,
          0.3395, -0.2083],
        [-0.1517, -0.7108,  0.3556,  0.0333, -0.0869,  0.1280, -0.3427,  0.2008,
         -0.0807,  0.3396]], grad_fn=<AddmmBackward0>)
MLP(
  (hidden): Linear(in_features=20, out_features=256, bias=True)
  (output): Linear(in_features=256, out_features=10, bias=True)
)
